export const IS_FETCHING_TODOS = 'IS_FETCHING_TODOS';
export const DID_FETCH_TODOS = 'DID_FETCH_TODOS';
export const DID_ADD_TODO = 'DID_ADD_TODO';
export const DID_RECEIVE_TODOS = 'DID_RECEIVE_TODOS';
export const DID_UPDATE_TODO = 'DID_UPDATE_TODO';
export const DID_CHANGE_TODO = 'DID_CHANGE_TODO';
export const DID_DELETE_TODO = 'DID_DELETE_TODO';
